import argparse
import json
import logging
import re
import sys
from pathlib import Path
from typing import Any, Iterable

from src.offline.finite_state_machine import ExecutionSegment, LogTransition, StaticLogFSM
from src.offline.flow import (
    SemanticEdge,
    SemanticFlowGraph,
    SemanticUnit,
    SemanticUnitKind,
    VariableKind,
    VariableRef,
)

from src.offline.log import LogTemplate, TrieNode
from src.visual.flow import draw_semantic_graph_graphviz
from src.visual.fsm import draw_log_fsm_graphviz
from src.visual.trie import visualize_trie_matplotlib


logger = logging.getLogger("visualize")


# --------------------------------------------------------------------------- #
# Generic serialization helpers
# --------------------------------------------------------------------------- #

def safe_name(value: str) -> str:
    """Create a stable filesystem-safe component from an entrypoint or method name."""
    normalized = re.sub(r"[^A-Za-z0-9._-]+", "_", value or "unnamed")
    return normalized.strip("._") or "unnamed"


def enum_value(enum_type, raw: Any, default):
    """Restore a StrEnum member from JSON, falling back safely for unknown values."""
    if isinstance(raw, enum_type):
        return raw
    try:
        return enum_type(str(raw))
    except ValueError:
        return default


def tuple_or_empty(value: Any) -> tuple:
    """Restore tuple semantics after JSON has converted tuples to lists."""
    return tuple(value) if value is not None else ()


def restore_variable(raw: dict[str, Any]) -> VariableRef:
    """Restore VariableRef from the dict generated by builder.py serialize_flow()."""
    return VariableRef(
        name=str(raw.get("name", "")),
        declaration_node_id=raw.get("declaration_node_id"),
        type_full_name=str(raw.get("type_full_name", "")),
        kind=enum_value(VariableKind, raw.get("kind"), VariableKind.UNKNOWN),
    )


# --------------------------------------------------------------------------- #
# Trie artifact deserialization
# --------------------------------------------------------------------------- #

def restore_trie_node(raw_node: dict[str, Any]) -> TrieNode:
    """Recursively restore TrieNode from builder.py's trie.json structure."""
    terminals = [
        LogTemplate(
            call_node_id=str(raw_template["call_node_id"]),
            raw_template=str(raw_template["raw_template"]),
            tokens=list(raw_template.get("tokens", [])),
            static_count=int(raw_template.get("static_count", 0)),
        )
        for raw_template in raw_node.get("terminals", [])
    ]
    children = {
        token: restore_trie_node(child)
        for token, child in raw_node.get("children", {}).items()
    }
    return TrieNode(children=children, terminals=terminals)


def load_trie(trie_path: Path) -> tuple[TrieNode, int]:
    """Load a serialized Log Trie from output/<service>/trie.json."""
    payload = json.loads(trie_path.read_text(encoding="utf-8"))
    raw_root = payload.get("trie")
    if not isinstance(raw_root, dict):
        raise ValueError(f"Invalid Trie artifact: missing object field 'trie' in {trie_path}")
    return restore_trie_node(raw_root), int(payload.get("templates_total", 0))


# --------------------------------------------------------------------------- #
# FLOW artifact deserialization
# --------------------------------------------------------------------------- #

def load_flow_graphs(flow_path: Path) -> tuple[str, dict[str, SemanticFlowGraph]]:
    """
    Restore SemanticFlowGraph objects from one <entrypoint>.flow.json file.

    builder.py stores all reachable methods under the top-level `methods`
    mapping. Renderer modules receive only typed graph objects, so JSON
    reconstruction remains isolated in this CLI module.
    """
    payload = json.loads(flow_path.read_text(encoding="utf-8"))
    entrypoint_name = str(payload.get("entrypoint_name") or flow_path.stem.removesuffix(".flow"))
    graphs: dict[str, SemanticFlowGraph] = {}

    for method_name, raw_graph in payload.get("methods", {}).items():
        graph = SemanticFlowGraph(
            method_node_id=str(raw_graph.get("method_node_id", "")),
            method_full_name=method_name,
            start_node_id=str(raw_graph.get("start_node_id", f"start@{method_name}")),
            return_node_ids=set(raw_graph.get("return_node_ids", [])),
            input_parameters=[tuple(item) for item in raw_graph.get("input_parameters", [])],
            output_parameters=[tuple(item) for item in raw_graph.get("output_parameters", [])],
        )

        for raw_unit in raw_graph.get("nodes", []):
            unit = SemanticUnit(
                node_id=str(raw_unit["node_id"]),
                kind=enum_value(SemanticUnitKind, raw_unit.get("kind"), SemanticUnitKind.UNKNOWN),
                code=str(raw_unit.get("code", "")),
                line=str(raw_unit.get("line", "")),
                raw_cfg_node_ids=list(raw_unit.get("raw_cfg_node_ids", [])),
                defines=[restore_variable(item) for item in raw_unit.get("defines", [])],
                uses=[restore_variable(item) for item in raw_unit.get("uses", [])],
                # Current builder.py FLOW JSON intentionally omits DataDependency.
                dependencies=[],
                call_node_ids=list(raw_unit.get("call_node_ids", [])),
                callee_full_names=list(raw_unit.get("callee_full_names", [])),
                internal_callee_full_names=list(raw_unit.get("internal_callee_full_names", [])),
            )
            graph.nodes[unit.node_id] = unit

        for raw_edge in raw_graph.get("edges", []):
            edge = SemanticEdge(
                source_id=str(raw_edge["source_id"]),
                target_id=str(raw_edge["target_id"]),
                condition=str(raw_edge.get("condition", "")),
            )
            graph.edges[(edge.source_id, edge.target_id, edge.condition)] = edge

        graphs[method_name] = graph

    return entrypoint_name, graphs


# --------------------------------------------------------------------------- #
# FSM artifact deserialization
# --------------------------------------------------------------------------- #

def load_fsm(fsm_path: Path) -> StaticLogFSM:
    """
    Restore StaticLogFSM from one <entrypoint>.fsm.json file.

    JSON stores states as a list while StaticLogFSM requires a dictionary keyed
    by state id. start_states and terminals are derived StaticLogFSM properties
    and are recomputed from the state flags.
    """
    payload = json.loads(fsm_path.read_text(encoding="utf-8"))

    states: dict[str, ExecutionSegment] = {}
    for raw_state in payload.get("states", []):
        state = ExecutionSegment(
            id=str(raw_state["id"]),
            entrypoint_full_name=str(raw_state.get("entrypoint_full_name", "")),
            method_full_name=str(raw_state.get("method_full_name", "")),
            direct_methods=tuple_or_empty(raw_state.get("direct_methods")),
            external_calls=tuple_or_empty(raw_state.get("external_calls")),
            conditions=tuple_or_empty(raw_state.get("conditions")),
            previous_log_call_node_id=raw_state.get("previous_log_call_node_id"),
            next_log_call_node_id=raw_state.get("next_log_call_node_id"),
            is_start=bool(raw_state.get("is_start", False)),
            is_terminal=bool(raw_state.get("is_terminal", False)),
            kind=str(raw_state.get("kind", "INCOMPLETE_SEGMENT")),
        )
        states[state.id] = state

    transitions = [
        LogTransition(
            id=str(raw_transition["id"]),
            source_segment_id=str(raw_transition["source_segment_id"]),
            target_segment_id=str(raw_transition["target_segment_id"]),
            template=str(raw_transition.get("template", "")),
            log_call_node_id=str(raw_transition.get("log_call_node_id", "")),
            method_full_name=str(raw_transition.get("method_full_name", "")),
            method_node_id=str(raw_transition.get("method_node_id", "")),
            conditions=tuple_or_empty(raw_transition.get("conditions")),
            static_score=int(raw_transition.get("static_score", 0)),
        )
        for raw_transition in payload.get("transitions", [])
    ]

    return StaticLogFSM(
        entrypoint_node_id=str(payload.get("entrypoint_node_id", "")),
        entrypoint_name=str(payload.get("entrypoint_name", fsm_path.stem.removesuffix(".fsm"))),
        entrypoint_full_name=str(payload.get("entrypoint_full_name", "")),
        states=states,
        transitions=transitions,
        warnings=list(payload.get("warnings", [])),
    )


# --------------------------------------------------------------------------- #
# Artifact discovery and rendering
# --------------------------------------------------------------------------- #

def render_service_artifacts(
    input_dir: Path,
    output_dir: Path,
    entrypoint_filter: str | None = None,
    only: str = "all",
    fmt: str = "png",
    rankdir: str = "LR",
) -> list[dict[str, Any]]:
    """Render selected Trie, FLOW, and FSM artifacts from one service folder."""
    output_dir.mkdir(parents=True, exist_ok=True)
    index: list[dict[str, Any]] = []

    trie_path = input_dir / "trie.json"
    flow_paths = sorted(input_dir.glob("*.flow.json")) if only in {"all", "flow"} else []
    fsm_paths = sorted(input_dir.glob("*.fsm.json")) if only in {"all", "fsm"} else []

    if entrypoint_filter:
        flow_paths = [path for path in flow_paths if path.name == f"{entrypoint_filter}.flow.json"]
        fsm_paths = [path for path in fsm_paths if path.name == f"{entrypoint_filter}.fsm.json"]

    wants_trie = only in {"all", "trie"}
    if wants_trie and not trie_path.exists():
        logger.warning("Trie rendering skipped: artifact not found: %s", trie_path)

    if not flow_paths and not fsm_paths and not (wants_trie and trie_path.exists()):
        raise FileNotFoundError(
            f"No matching artifacts found in {input_dir}. Expected trie.json, "
            "<entrypoint>.flow.json, or <entrypoint>.fsm.json."
        )

    # All renderer calls intentionally go through src.offline.visual facade.
    if wants_trie and trie_path.exists():
        try:
            root, template_count = load_trie(trie_path)
            rendered_path = output_dir / "trie.png"
            visualize_trie_matplotlib(root, output_path=str(rendered_path))
            index.append({
                "artifact_type": "trie",
                "source_file": trie_path.name,
                "status": "ok",
                "rendered_file": str(rendered_path),
                "templates": template_count,
            })
            logger.info("Trie: rendered %d template(s) -> %s", template_count, rendered_path)
        except Exception as error:
            logger.exception("Failed to render Trie")
            index.append({
                "artifact_type": "trie",
                "source_file": trie_path.name,
                "status": "error",
                "error": f"{type(error).__name__}: {error}",
            })

    for flow_path in flow_paths:
        entrypoint_name, graphs = load_flow_graphs(flow_path)
        entrypoint_output_dir = output_dir / "flow" / safe_name(entrypoint_name)
        logger.info("FLOW %s: rendering %d method graph(s)", entrypoint_name, len(graphs))

        for method_name, graph in graphs.items():
            try:
                rendered_path = draw_semantic_graph_graphviz(
                    semantic_graph=graph,
                    filename=safe_name(method_name),
                    output_dir=str(entrypoint_output_dir),
                    fmt=fmt,
                    rankdir=rankdir,
                )
                index.append({
                    "artifact_type": "flow",
                    "entrypoint": entrypoint_name,
                    "method": method_name,
                    "source_file": flow_path.name,
                    "status": "ok",
                    "rendered_file": str(rendered_path),
                    "nodes": len(graph.nodes),
                    "edges": len(graph.edges),
                })
            except Exception as error:
                logger.exception("Failed to render FLOW method %s", method_name)
                index.append({
                    "artifact_type": "flow",
                    "entrypoint": entrypoint_name,
                    "method": method_name,
                    "source_file": flow_path.name,
                    "status": "error",
                    "error": f"{type(error).__name__}: {error}",
                })

    for fsm_path in fsm_paths:
        try:
            fsm = load_fsm(fsm_path)
            entrypoint_name = fsm.entrypoint_name or fsm_path.stem.removesuffix(".fsm")
            rendered_path = draw_log_fsm_graphviz(
                fsm=fsm,
                filename=safe_name(entrypoint_name),
                output_dir=str(output_dir / "fsm"),
                fmt=fmt,
                rankdir=rankdir,
            )
            index.append({
                "artifact_type": "fsm",
                "entrypoint": entrypoint_name,
                "source_file": fsm_path.name,
                "status": "ok",
                "rendered_file": str(rendered_path),
                "states": len(fsm.states),
                "transitions": len(fsm.transitions),
            })
            logger.info("FSM %s: rendered %d state(s), %d transition(s)",
                        entrypoint_name, len(fsm.states), len(fsm.transitions))
        except Exception as error:
            logger.exception("Failed to render FSM artifact %s", fsm_path.name)
            index.append({
                "artifact_type": "fsm",
                "source_file": fsm_path.name,
                "status": "error",
                "error": f"{type(error).__name__}: {error}",
            })

    (output_dir / "index.json").write_text(
        json.dumps(index, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    return index


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #

def parse_args(argv: Iterable[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render builder.py Trie, FLOW, and FSM artifacts from a service folder."
    )
    parser.add_argument("--input-dir", type=Path, required=True,
                        help="Service artifact directory, e.g. output/frontend")
    parser.add_argument("--output-dir", type=Path, default=None,
                        help="Output directory (default: <input-dir>/visualizations)")
    parser.add_argument("--entrypoint", type=str, default=None,
                        help="Render only this entrypoint's FLOW/FSM artifacts; Trie remains service-wide")
    parser.add_argument("--only", choices=("all", "trie", "flow", "fsm"), default="all")
    parser.add_argument("--format", choices=("png", "svg", "pdf"), default="png",
                        help="Graphviz output format for FLOW/FSM; Trie always renders as PNG")
    parser.add_argument("--rankdir", choices=("LR", "TB", "RL", "BT"), default="LR")
    parser.add_argument("-v", "--verbose", action="store_true")
    return parser.parse_args(argv)


def main(argv: Iterable[str] | None = None) -> int:
    args = parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%H:%M:%S",
    )

    if not args.input_dir.is_dir():
        raise FileNotFoundError(f"Input directory does not exist: {args.input_dir}")

    output_dir = args.output_dir or args.input_dir / "visualizations"
    index = render_service_artifacts(
        input_dir=args.input_dir,
        output_dir=output_dir,
        entrypoint_filter=args.entrypoint,
        only=args.only,
        fmt=args.format,
        rankdir=args.rankdir,
    )

    rendered = sum(1 for item in index if item["status"] == "ok")
    failed = sum(1 for item in index if item["status"] == "error")
    logger.info("Done: rendered=%d failed=%d output=%s", rendered, failed, output_dir)
    return 0 if failed == 0 else 1


if __name__ == "__main__":    
    sys.exit(main())